core/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views import generic
from material.frontend import urls as frontend_urls

# from core.views import create_custom_model, MyDynRefView
from core.views import attach_upload

urlpatterns = [
    url('^file/upload/$', attach_upload, name='attach-upload')
]

favorit5/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views import generic
from material.frontend import urls as frontend_urls
from service_desk import urls as sd_urls

# from core.views import create_custom_model, MyDynRefView
import core.urls as core_urls
from favorit5 import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^core/', include(core_urls)),
    # url(r'^select2/', include('django_select2.urls')),
    url(r'^sd/', include(sd_urls)),

    url(r'^$', generic.RedirectView.as_view(url='/workflow/', permanent=False)),
    url(r'', include(frontend_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service_desk/urls.py
from django.conf.urls import url

from service_desk.views import CustomerListView

urlpatterns = [
    url(r'api/customer/list', CustomerListView.as_view(), name='customer-list'),
]

service_desk/models.py
from django.contrib.auth.models import User
from django.db import models
# Create your models here.
from django.template import Template, Context
from model_utils.managers import InheritanceManager
from viewflow.models import Process

from bpm.models import Status
from core import auto_number
from core.models import AbstractBranchedModel, Reference  # , Attach
from django.utils.translation import ugettext_lazy as _


# VersionedObject, Version, Document, \

class HelloWorldProcess(Process):
    text = models.CharField(_('text'),max_length=150)
    approved = models.BooleanField(_('approved'),default=False)

    # class Meta:
    #     verbose_name=_('hello world process')
    #     verbose_name = _('hello world processes')


class Tracker(Reference):
    pass

    class Meta:
        verbose_name=_('tracker')
        verbose_name_plural=_('trackers')


class ActiveObjects(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(blocked=False)




class Customer(Reference):
    blocked = models.BooleanField(_('blocked'),default=False)
    objects = ActiveObjects()
    all_customers = models.Manager()

    class Meta:
        verbose_name=_('customer')
        verbose_name_plural=_('customers')

    def __str__(self):
        return self.name


class AbstractDocument(AbstractBranchedModel):
    class Meta:
        abstract = True
        # verbose_name=_('abstract document')

    number = models.CharField(_('number'),max_length=255)
    on_date = models.DateTimeField(_('on date'),auto_now_add=True)

    def __str__(self):
        return self.number and self.number or ("Документ без номера от %s" % self.on_date)


class ServiceObject(Reference):
    pass

    class Meta:
        verbose_name=_('service object')
        verbose_name_plural=_('service objects')


class AccessObject(Reference):
    pass

    class Meta:
        verbose_name=_('access object')
        verbose_name_plural=_('access objects')


@auto_number
class Intro(AbstractDocument):
    """
    документ Обращение
    """

    class Meta:
        verbose_name = u'Обращение'
        verbose_name_plural = u'Обращения'
        ordering = ['-on_date']

    customer = models.ForeignKey(Customer, null=True, blank=True,verbose_name=_('customer'))
    description = models.TextField(_('description'))
    answered = models.BooleanField(_('answered'),default=True)
    trackers = models.ManyToManyField(Tracker,verbose_name=_('trackers'))

    def __str__(self):
        short_desc = self.description[:45] + (self.description[45:] and "..")
        return "№{doc_number} от {doc_date}({customer}: {short_desc})".format(
            doc_date=self.on_date.strftime("%Y-%m-%d %H:%M"),
            doc_number=self.number,
            customer=self.customer,
            short_desc=short_desc)


class IntroProcess(Process):
    class Meta:
        verbose_name = "Процесс обращение"
        verbose_name_plural = "Процессы обращения"

    document = models.ForeignKey(Intro,verbose_name=_('document'))


class Request(AbstractDocument):
    objects = InheritanceManager()
    CATEGORY_CHOICES = (('INCIDENT', 'Инцидент'), ('SERVICE', 'Запрос на обслуживание'), ('ACCESS', 'Запрос на доступ'))
    LEVEL = (('HIGH', 'Высокий'), ('MIDDLE', 'Средний'), ('LOW', 'НИЗКИЙ'))
    PRIORITY_LEVEL = (('CRITICAL', 'Критический'), ('HIGH', 'Высокий'), ('MIDDLE', 'Средний'), ('LOW', 'НИЗКИЙ'),
                      ('PLAN', 'Планирование'))
    DEFAULT_CATEGORY = 'INCIDENT'
    intro = models.ForeignKey(Intro, null=True, blank=True,verbose_name=_('intro'))
    category = models.CharField(_('category'),max_length=255)
    customer = models.ForeignKey(Customer,verbose_name=_('customer'))
    customer_description = models.TextField(_('customer description'))
    employee_description = models.TextField(_('employee description'))
    impact = models.CharField(_('impact'),max_length=25, choices=LEVEL, default='LOW')
    urgency = models.CharField(_('urgency'),max_length=25, choices=LEVEL, default='LOW')
    priority = models.CharField(_('priority'),max_length=25, choices=PRIORITY_LEVEL, default='LOW')
    started_at = models.DateTimeField(_('started at'),auto_now_add=True)
    deadline = models.DateTimeField(_('deadline'))
    status = models.ForeignKey(Status, blank=True, null=True,verbose_name=_('status'))
    taken_by = models.ForeignKey(User,verbose_name=_('taken by'))

    # attaches = models.ManyToManyField(Attach)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.pk and not self.category:
            self.category = self.DEFAULT_CATEGORY


@auto_number
class Incident(Request):
    def clean(self):
        if self.intro:
            print(self.intro.customer)
            self.customer = self.intro.customer
        if self.intro and not self.customer_description:
            self.customer_description = self.intro.description

    class Meta:
        verbose_name=_('incident')
        verbose_name_plural=_('incidents')


@auto_number
class ServiceRequest(Request):
    DEFAULT_CATEGORY = 'SERVICE'
    service_object = models.ForeignKey(ServiceObject,verbose_name=_('service object'))

    class Meta:
        verbose_name=_('service request')
        verbose_name_plural=_('service requests')


@auto_number
class AccessRequest(Request):
    DEFAULT_CATEGORY = 'ACCESS'
    access_object = models.ForeignKey(AccessObject,verbose_name=_('access object'))

    class Meta:
        verbose_name=_('access request')
        verbose_name_plural=_('access requests')


class RequestAnswer(models.Model):
    answer = models.TextField(_('answer'))
    request = models.ForeignKey(Request,verbose_name=_('request'))
    answered_at = models.DateTimeField(auto_now_add=True,verbose_name=_('answered at'))
    answered_person = models.ForeignKey(User,verbose_name=_('answered_person'))


class EscalationLevel(Reference):
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        # TODO: переделать механизм регистрации прав при добавлении нового элемента справочника
        from django.core.management import call_command
        call_command('makemigrations')
        call_command('migrate')

    class Meta:
        verbose_name=_('escalation level')
        verbose_name_plural=_('escalation levels')


class RequestProcess(Process):
    class Meta:
        verbose_name = u'Процесс - Заявка'
        verbose_name_plural = u'Процессы - Заявки'

    request = models.ForeignKey(Request,verbose_name=_('request'))
    escalation_level = models.ForeignKey(EscalationLevel, blank=True, null=True,verbose_name=_('escalation level'))

    def summary(self):
        """Quick textual process state representation for end user."""
        if self.flow_class and self.flow_class.process_class == type(self):
            return Template(
                self.flow_class.summary_template
            ).render(
                Context({'process': self, 'flow_class': self.flow_class})
            )

        return "{} - {}".format(self.flow_class.process_title, self.request.status)

    def __str__(self):
        if self.flow_class:
            return '{} #{}'.format(self.flow_class.process_title, self.pk)
        return "<Process {}> - {}".format(self.pk, self.request.status)


class IncidentProcess(RequestProcess):
    class Meta:
        verbose_name = 'Процесс - Инцидент'
        verbose_name_plural = 'Процессы - Инцидент'


class AccessRequestProcess(RequestProcess):
    class Meta:
        verbose_name = 'Процесс - Предоставление доступа'
        verbose_name_plural = 'Процессы - Предоставление доступа'


class ServiceRequestProcess(RequestProcess):
    class Meta:
        verbose_name = 'Процесс - Сервисное обслуживание'
        verbose_name_plural = 'Процессы - Сервисное обслуживание'


@auto_number
class TDA(AbstractDocument):
    intro = models.ForeignKey(Intro, blank=True, null=True,verbose_name=_('intro'))
    info = models.TextField(_('info'))

    def __str__(self):
        return "№{doc_number} от {doc_date}".format(
            doc_date=self.on_date.strftime("%Y-%m-%d %H:%M"),
            doc_number=self.number)


class DevelopmentProcess(Process):
    class Meta:
        verbose_name = 'Процесс - разработка'
        verbose_name_plural = 'Процессы - разработки'

    document = models.ForeignKey(TDA,verbose_name=_('document'))


class PerfomanceTest(models.Model):
    """тест разработки"""
    passed = models.BooleanField(default=False, verbose_name='Пройдено?')
    info = models.TextField(verbose_name='Условия тестирования')
    result = models.TextField(verbose_name='Описание резульатата тестирования')
    tda = models.ForeignKey(TDA)

service_desk/forms.py
from django import forms
import bpm.models
from bpm.models import Status
from service_desk.models import Customer, Intro, EscalationLevel
from . import models
from django.utils.translation import ugettext_lazy as _


class RequestForm(forms.ModelForm):
    # customer = forms.ModelChoiceField(required=False, queryset=Customer.objects.all())
    customer_description = forms.CharField(required=False, widget=forms.Textarea,label=_('Customer description'))
    intro = forms.ModelChoiceField(queryset=Intro.objects.filter(answered=False),label=_('Intro'))

    class Meta:
        model = models.Request
        fields = '__all__'
        widgets = {
            'customer': forms.TextInput(attrs={'data-url': '/sd/api/customer/list'}),
        }

    def clean(self):
        intro = self.cleaned_data.get('intro')
        customer = self.cleaned_data.get('customer')
        descr = self.cleaned_data.get('customer_description')
        self.data = self.data.copy()
        if intro and not customer:
            self.cleaned_data['customer'] = intro.customer
            self.data['customer'] = str(intro.customer_id)
        elif not customer:
            self.add_error('customer', 'Обязательное поле или выбирите Обращение')
        if intro and customer and intro.customer != customer:
            self.add_error('customer', 'Клиент должен совпадать с клиентом в Обращение (%s)' % intro.customer)
        if intro and not descr:
            self.cleaned_data['customer_description'] = intro.description
            self.data['customer_description'] = intro.description
        elif not descr:
            self.add_error('customer_description', 'Обязательное поле')
        return self.cleaned_data


class IncidentForm(RequestForm):
    class Meta:
        model = models.Incident
        fields = '__all__'
        exclude = ('status', 'category', 'taken_by', 'number', 'attachments')
        widgets = {
            'customer': forms.TextInput(attrs={'data-url': '/sd/api/customer/list'}),
        }

class IncidentCloseForm(forms.Form):
    status = forms.ChoiceField()
    result = forms.TextInput()


class ServiceRequestForm(RequestForm):
    class Meta:
        model = models.ServiceRequest
        fields = '__all__'
        exclude = ('status', 'category', 'taken_by', 'number', 'attachments')
        widgets = {
            'customer': forms.TextInput(attrs={'data-url': '/sd/api/customer/list'}),
        }


class AccessRequestForm(RequestForm):
    class Meta:
        model = models.AccessRequest
        fields = '__all__'
        exclude = ('status', 'category', 'taken_by', 'number', 'attachments')
        widgets = {
            'customer': forms.TextInput(attrs={'data-url': '/sd/api/customer/list'}),
        }


class IntroForm(forms.ModelForm):
    class Meta:
        model = models.Intro
        fields = '__all__'
        exclude = ('number',)
        widgets = {
            'customer': forms.TextInput(attrs={'data-url': '/sd/api/customer/list'})
        }



class AnswerForm(forms.ModelForm):
    status = forms.ModelChoiceField(queryset=Status.objects.filter(code__in=['solved', 'canceled']))
    escalation_level = forms.ModelChoiceField(queryset=EscalationLevel.objects.all(), required=False)
    class Meta:
        model = models.RequestAnswer
        fields = '__all__'
        exclude = ('request', 'answered_person')


class AvailableProcessTaskForm(forms.ModelForm):
    choice = forms.ChoiceField()

    class Meta:
        model = bpm.models.AvailableProcessTask
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(AvailableProcessTaskForm, self).__init__(*args, **kwargs)
        from django.apps import apps
        cfg = apps.get_app_config('viewflow_frontend')
        __PROCESS_CHOICES = ()
        for flow_meta_class in cfg._registry:
            for node_name in flow_meta_class._meta._nodes_by_name:
                node = flow_meta_class._meta._nodes_by_name[node_name]
                if node.task_type == 'HUMAN':
                    __PROCESS_CHOICES += (("%s.%s" % (flow_meta_class._meta.flow_label, node_name),
                                           "%s.%s" % (flow_meta_class.process_title, node.task_title)),)
        self.fields['choice'].choices = __PROCESS_CHOICES


class TDAForm(forms.ModelForm):
    intro = forms.ModelChoiceField(required=False, queryset=Intro.objects.filter(answered=False),label=_('Intro'))
    class Meta:
        model = models.TDA
        fields = '__all__'
        exclude = ('number',)


class PerfomanceTestForm(forms.ModelForm):
    class Meta:
        model = models.PerfomanceTest
        fields = ('info', 'result', 'passed')
        exclude = ('tda',)

    def empty_form(self):
        if hasattr(self, 'cleaned_data'):
            tmp_info = self.cleaned_data.get('info')
            tmp_result = self.cleaned_data.get('result')
            return (not tmp_info and not tmp_result)
        else:
            return False #нестандартное поведение, т.к. форма еще не проходила валидацию

class PerfomanceTestPassForm(forms.ModelForm):
    # info = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    # result = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    class Meta:
        model = models.PerfomanceTest
        fields = '__all__'
        exclude = ('tda', )
        widgets = {
            'passed': forms.CheckboxInput(attrs={'class':'filled-in'})
        }

service_desk/templates/service_desk/incident/implementation.html
{% extends 'viewflow/flow/task.html' %}

{% block task_form %}
    <div>
        <div style="margin-top: 10px !important;">
            <div class="row">
                <div class="col s12 align-left"><b> Информация от клиента:</b></div>
            </div>
            <div class="row">
                <div class="col s12 align-left">{{ activation.process.request.customer_description }}</div>
            </div>
            <div class="row">
                {% if add_info.access_object.code %}
                <div class="col s12 align-left">
                    [{{ add_info.access_object.code }}] {{ add_info.access_object.name }}
                </div>
                {% endif %}
                {% if add_info.service_object.code %}
                <div class="col s12 align-left">
                    [{{ add_info.service_object.code }}] {{ add_info.service_object.name }}
                </div>
                {% endif %}
            </div>

        </div>

        <div style="margin-top: 10px !important;">
            <div class="row">
                <div class="col s12 align-left"><b> Информация от 1й линии: </b></div>
            </div>
            <div class="row">
                <div class="col s12 align-left">{{ activation.process.request.employee_description }}</div>
            </div>
        </div>
        <div style="margin-top: 10px !important;">
            <div class="row">
                <div class="col s12 align-left"><b>Результаты выполнения:</b></div>
            </div>
            <div class="row">
                <div class="col s12">
                    <table>
                        {% for ans in activation.process.request.requestanswer_set.iterator %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ ans.answer }}</td>
                                <td>{{ ans.answered_person }}</td>
                                <td>{{ ans.answered_at }}</td>
                            </tr>
                        {% endfor %}
                    </table>

                </div>
            </div>
        </div>

    </div>
    {{ block.super }}
{% endblock %}

service_desk/templates/service_desk/incident/start_flow.html
{% extends 'viewflow/flow/start.html' %}

{% block left-panel %}
    {{ block.super }}
    <script>
        $(document).ready(function () {
            console.log("{{ form.data.customer }}");
            var current_id = {% if form.data.customer %} {{ form.data.customer }} {% else %} 0 {% endif %};
            var current_text = '';
            var hidden_input = $('#id_customer');
            var label = $("label[for='"+$(hidden_input).attr('id')+"']");
            var data_url = hidden_input.attr('data-url');
            if (data_url) {
                hidden_input.after('<input type="text" id="id_customer_autocomplete" name="customer_autocomplete" autocomplete="off" class="autocomplete"><label for="id_customer_autocomplete">Клиент</label>');
                hidden_input.hide();
                label.hide();
                $.get(data_url).done(function (data) {
                    var obj = jQuery.parseJSON(data);
                    var result = {};
                    var sourceData = {}
                    for (idx in obj) {
                        var text = '[' + obj[idx].code + '] ' + obj[idx].name
                        sourceData[text] = null;
                        result[text] = obj[idx];
                        if (obj[idx].pk == current_id) {
                            current_text = text;
                        }
                    }
                    var ac =$('#id_customer_autocomplete').autocomplete({
                        limit: 20,
                        minLength: 1,
                        data : sourceData,
                        onAutocomplete: function (val) {
                            hidden_input.val(result[val].pk);
                        }
                    });
                    if (current_text){
                        $('#id_customer_autocomplete').val(current_text);
                        $('#id_customer_autocomplete').trigger('click');
                    }
                });
            } else {
                console.log("No data url!!!");
            }
        });


    </script>
{% endblock %}